# Generated by Django 4.2.11 on 2024-03-28 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('face_descriptor', models.BinaryField()),
                ('photo', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sighting_time', models.DateTimeField(auto_now_add=True)),
                ('camera_photo', models.BinaryField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraUI.person')),
            ],
        ),
    ]
